[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [ "graph-file", "graph-lib", "tests"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
thiserror = "1.0.58"
